### PR TITLE
bring feeds back to life

### PR DESCRIPTION
**Pull request by alexh-name**
Don't know if you had sth different in mind for the refactoring, but this would bring back feeds for now.

### CODE REVIEW

**Comment by Ypnose** [comment]
Indeed, I have something different in mind, but it still remains foggy to me and probably for the users (it's not unmaintained). <code>wswsh</code> always had bad performance, because the directories are scanned two times plus the numerous <code>awk(1)</code> processes, when the feed is turned on. It's not a big deal since it's not a critical script, but the refactoring was started to solve that problem.

The goal is to apply all those actions with a simple scan. Unfortunately, I do not know how to "extract" page(s) added in the feed vs the regular page(s). Modifying file structure could be a way, but that's a lazy turn for a big problem. I thought about this problem and for now, I'm unable to write sexy lines.

If possible, I would also avoid trying to restore those old lines. I deleted them for this reason: the <code>SORD</code> is totally unmaintainable (I'm ashamed to see I did something that sucky). I suggest you to remain with your branch until I find a better idea before this summer. I **thank** you for the work too, and all the same for using / experimenting <code>wswsh</code>. The issue will not be closed, to show you I want to solve it.

**Comment by Ypnose** [comment]
Oh BTW Alex, if you have something serious in mind, do not hesitate to explain it here. I'm currently trying to solve that obstacle.

**Comment by alexh-name** [comment]
I only saw your newest comment now, sorry. I had some thoughts on it and plans to try it out. I'll try to explain. I also wanted to change some functionality in the process. I thought that it would be nice if you could have articles for the feed in any directory.

Solutions I had started to think on:

- Scanning the directories in src/ only once, storing them in an array for later use
- Using grep to identify files containing a string used for blog markup, instead of expecting all blog articles in src/blog/

I think this is the most promising I could come up with. I don't know how the impact on performance will be though.

Would do you think? What are your plans for now?

**Comment by Ypnose** [comment]
I will try to address all things you pointed out:

> I thought that it would be nice if you could have articles for the feed in any directory.

Indeed, it sounds reasonable.

> Scanning the directories in src/ only once, storing them in an array for later use

IIRC, that was one of my first idea. The problem was: how to detect those articles and then, how to sort them by date (ideally in reverse)? That would involves too much alchemy, like it was already done with <code>awk(1)</code>.

> Using grep to identify files containing a string used for blog markup, instead of expecting all blog articles in src/blog/

Hum, much better, but the previous issue about sorting them according to the date is still unsolved.

After a serious reflection on this matter, I decided to add a new variable in <code>wswsh.conf</code>, which will contain the articles paths (an array could do the trick but it doesn't change much). The user must write the name for every new article, as it is not so painful (and also save many LOC in <code>wswsh</code>). This is by far, the simplest way to do it.  
It has two (or even three) advantages: 
 * You can include any article from any directory.
 * Avoid complexity (the user HAS to sort the article by himself) and prevent another scan
 * The file structure is not altered
It looks promising. I will see how if everything goes as I planned…

**Comment by alexh-name** [comment]
This all seems very reasonable!

**Comment by Ypnose** [comment]
The "benchmark" was almost a success. The new version should hit the repo this summer, as I told it 2 months ago.

**Comment by alexh-name** [comment]
Great news!

**Comment by Ypnose** [comment]
wswsh: restore feed via atom.xml → 868534d

**Comment by Ypnose** [comment]
The feed is now restored. Closing.

**Pull request closed without merging**
